POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsbyIsImlkIjoiNjMyMDg5MTc3Y2M3ZGQwM2YyZjE2MmMwIiwiaWF0IjoxNjYzMDg5NjQyLCJleHAiOjE2NjMwOTMyNDJ9.zml2dFNkldFmk5JaUAU6w1TCLYhAXbb6uBoglugbYSk

{
	"content": "Test token",
	"important": true
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}